name: Build Webpack and generate PDFs
on:
  push:
    branches-ignore: [master]

# Allow one concurrent build for each branch
concurrency:
  group: build-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # Read-only permissions for GITHUB_TOKEN
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build CV
        run: |
          npm install
          npm run build:cv

      - name: Generate PDF file (en)
        uses: fifsky/html-to-pdf-action@v0.1.0
        with:
          htmlFile: ./build/cv.html?language=en&print
          outputFile: ./src/pages/cv/files/cv_en.pdf

      - name: Generate PDF file (ru)
        uses: fifsky/html-to-pdf-action@v0.1.0
        with:
          htmlFile: ./build/cv.html?language=ru&print
          outputFile: ./src/pages/cv/files/cv_ru.pdf

      - name: Build the rest of the app
        env:
          GITHUB_REPO: ${{ github.repository }}
        run: |
          npm run build:main

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build/"
